name: QA Pipeline

on:

  #push:
    #branches:
      #- main

  #Ejecución a demanda
  workflow_dispatch:
    inputs:
      tags:
        description: 'Descripción del pipeline'
        required: true
        default: '@smoke'


jobs:
  build:
    runs-on: ubuntu-22.04
    ##aca

    steps:
      - name: Clonar  repositorio
        uses: actions/checkout@v3

      - name: Instación de Java 17 y Maven
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Ejecutar pruebas
        #run: mvn clean test "-Dkarate.options=--tags @smoke"
        run: mvn clean test "-Dkarate.tags=${{ inputs.tags }}"

      - name: Visualizar reporte
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-report
          path: target/karate-reports
          ##hola
